SELECT num FROM (
SELECT COALESCE(num,NULL) AS num
FROM MyNumbers
GROUP BY num
HAVING COUNT(num)=1
ORDER BY num DESC
LIMIT 1) AS t
UNION ALL
SELECT NULL
WHERE NOT EXISTS(SELECT 1
    FROM MyNumbers
    GROUP BY num
    HAVING COUNT(num) = 1);
